apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  labels:
    app: fraud-service
spec:
  selector:
    app: fraud-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
