apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app: wallet-service
spec:
  selector:
    app: wallet-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
