apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-wallet
  labels:
    app: postgres-wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-wallet
  template:
    metadata:
      labels:
        app: postgres-wallet
    spec:
      containers:
        - name: postgres-wallet
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: wallet_db
            - name: POSTGRES_USER
              value: wallet_user
            - name: POSTGRES_PASSWORD
              value: wallet_password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-wallet-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-wallet-storage
          persistentVolumeClaim:
            claimName: postgres-wallet-pvc
