apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-wallet-pvc
  labels:
    app: postgres-wallet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
