apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
  labels:
    app: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres-auth
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: auth_db
            - name: POSTGRES_USER
              value: auth_user
            - name: POSTGRES_PASSWORD
              value: auth_password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-auth-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-auth-storage
          persistentVolumeClaim:
            claimName: postgres-auth-pvc
