apiVersion: v1
kind: Service
metadata:
  name: postgres-wallet
  labels:
    app: postgres-wallet
spec:
  selector:
    app: postgres-wallet
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
