apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:1.0.0-SNAPSHOT # This image needs to be built locally or pushed to a registry
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
